url: Jingnan92.github.io
baseurl: /NewEventDataSite


# Site settings
title: UTD Event Data
email: xxx@utdallas.edu
description: # this means to ignore newlines until "baseurl:"
  Project funded by NSF RIDIR SBE-SMA-1539302
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://epps.utdallas.edu/" # the base hostname & protocol for your site
twitter_username: utdallas
github_username:  epps

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
